name: trader server
version: 0.0.1
description: Trader server for trader UI.
author: Agustin Berbegall <aberbegall@yahoo.es>
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  dson: any
  http: any
  redis_client: any
dev_dependencies:
  test: '>=0.12.0 <0.13.0'
