name: trader
version: 0.0.1
description: A minimal command-line application.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  dson: any
  http: any
  redis_client: any
dev_dependencies:
  unittest: any
